version: '3'
services:
  app:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - mongodb
    environment:
      - MONGO_URL=mongodb://mongodb:27017/my_db
      - DB_NAME=my_db
  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db
volumes:
  mongodb_data: